//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSO.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User argument is null.
        /// </summary>
        public static string Excpetion_UserArgumentIsNull {
            get {
                return ResourceManager.GetString("Excpetion_UserArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserConfiguration property in User shouldn&apos;t be null.
        /// </summary>
        public static string Excpetion_UserConfigurationIsNull {
            get {
                return ResourceManager.GetString("Excpetion_UserConfigurationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string IncorrectUserNameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with User ID {0} has multiple active sessions.
        /// </summary>
        public static string MultipleActiveSessionsFoundForUser {
            get {
                return ResourceManager.GetString("MultipleActiveSessionsFoundForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with user ID {0} has no active sessions found.
        /// </summary>
        public static string NoActiveSessionsFoundForUserWithID {
            get {
                return ResourceManager.GetString("NoActiveSessionsFoundForUserWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username {0} has no active sessions found.
        /// </summary>
        public static string NoActiveSessionsFoundForUserWithUsername {
            get {
                return ResourceManager.GetString("NoActiveSessionsFoundForUserWithUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Username {0} has active session.
        /// </summary>
        public static string UserHasActiveSessionAlready {
            get {
                return ResourceManager.GetString("UserHasActiveSessionAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username {0} doesn&apos;t have authorized sites.
        /// </summary>
        public static string UserHasNoAuthorizedSites {
            get {
                return ResourceManager.GetString("UserHasNoAuthorizedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} already exists.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
    }
}
