//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardData()
        {
            this.Membershipdatas = new HashSet<Membershipdata>();
        }
    
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> Issuedate { get; set; }
        public Nullable<System.DateTime> Deliverydate { get; set; }
        public Nullable<System.DateTime> Expiringdate { get; set; }
        public Nullable<System.DateTime> Requestdate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> MembershipNumber { get; set; }
    
        public virtual CardStatu CardStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membershipdata> Membershipdatas { get; set; }
    }
}
