//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contactinfo()
        {
            this.Membershipdatas = new HashSet<Membershipdata>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public int Contacttype { get; set; }
        public string Contactinfo1 { get; set; }
        public bool Active { get; set; }
    
        public virtual Contacttype Contacttype1 { get; set; }
        public virtual Personaldata Personaldata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membershipdata> Membershipdatas { get; set; }
    }
}
