//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GBTMembershipSolutionEntities : DbContext
    {
        public GBTMembershipSolutionEntities()
            : base("name=GBTMembershipSolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CardData> CardDatas { get; set; }
        public virtual DbSet<CardStatu> CardStatus { get; set; }
        public virtual DbSet<CitizenAddress> CitizenAddresses { get; set; }
        public virtual DbSet<CitizenID> CitizenIDs { get; set; }
        public virtual DbSet<CitizenIDType> CitizenIDTypes { get; set; }
        public virtual DbSet<ClubInfo> ClubInfoes { get; set; }
        public virtual DbSet<ClubInterest> ClubInterests { get; set; }
        public virtual DbSet<Contacttype> Contacttypes { get; set; }
        public virtual DbSet<educationdegreetype> educationdegreetypes { get; set; }
        public virtual DbSet<Educationsinfo> Educationsinfoes { get; set; }
        public virtual DbSet<jobcatogory> jobcatogories { get; set; }
        public virtual DbSet<JobInfo> JobInfoes { get; set; }
        public virtual DbSet<Membershipdata> Membershipdatas { get; set; }
        public virtual DbSet<Membershipinterest> Membershipinterests { get; set; }
        public virtual DbSet<Membershiptype> Membershiptypes { get; set; }
        public virtual DbSet<Memebershipstatu> Memebershipstatus { get; set; }
        public virtual DbSet<Payments_dues> Payments_dues { get; set; }
        public virtual DbSet<PersonalInterest> PersonalInterests { get; set; }
        public virtual DbSet<PersonalInterstsData> PersonalInterstsDatas { get; set; }
        public virtual DbSet<PremesisLimit> PremesisLimits { get; set; }
        public virtual DbSet<RelationType> RelationTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<RenewalData> RenewalDatas { get; set; }
        public virtual DbSet<Personaldata> Personaldatas { get; set; }
        public virtual DbSet<Contactinfo> Contactinfoes { get; set; }
    }
}
