//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membershipinterest
    {
        public int ID { get; set; }
        public Nullable<int> MembershipId { get; set; }
        public Nullable<int> clubinterestID { get; set; }
    
        public virtual ClubInterest ClubInterest { get; set; }
        public virtual Membershipdata Membershipdata { get; set; }
    }
}
