//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membershipdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membershipdata()
        {
            this.Membershipinterests = new HashSet<Membershipinterest>();
            this.Payments_dues = new HashSet<Payments_dues>();
            this.Payments_dues1 = new HashSet<Payments_dues>();
            this.PremesisLimits = new HashSet<PremesisLimit>();
            this.RenewalDatas = new HashSet<RenewalData>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<int> FK_defaultNationalId { get; set; }
        public Nullable<int> FK_defaultContactId { get; set; }
        public Nullable<int> FK_defaultaddressesId { get; set; }
        public Nullable<int> Fk_currentjobid { get; set; }
        public Nullable<int> FK_educationID { get; set; }
        public Nullable<int> Membershipstatus { get; set; }
        public Nullable<int> Membershiptype { get; set; }
        public Nullable<int> ClubID { get; set; }
        public string Membershipapplicationreference { get; set; }
        public Nullable<System.DateTime> Membershipapplicationdate { get; set; }
        public Nullable<int> recommeddationMembershipid { get; set; }
        public Nullable<bool> Ismainsupplementary { get; set; }
        public Nullable<int> RelationID { get; set; }
        public Nullable<System.DateTime> Lastrenwelldate { get; set; }
        public Nullable<System.DateTime> Nextrenwelldate { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> suspenddate { get; set; }
        public Nullable<int> MembershipID { get; set; }
        public Nullable<int> SSOID { get; set; }
    
        public virtual CitizenAddress CitizenAddress { get; set; }
        public virtual CitizenID CitizenID { get; set; }
        public virtual ClubInfo ClubInfo { get; set; }
        public virtual Educationsinfo Educationsinfo { get; set; }
        public virtual JobInfo JobInfo { get; set; }
        public virtual Membershiptype Membershiptype1 { get; set; }
        public virtual Memebershipstatu Memebershipstatu { get; set; }
        public virtual RelationType RelationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membershipinterest> Membershipinterests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments_dues> Payments_dues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments_dues> Payments_dues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremesisLimit> PremesisLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RenewalData> RenewalDatas { get; set; }
        public virtual CardData CardData { get; set; }
        public virtual Personaldata Personaldata { get; set; }
        public virtual Contactinfo Contactinfo { get; set; }
    }
}
