//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments_dues
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Paiddate { get; set; }
        public Nullable<int> Satus { get; set; }
        public string Duedescription { get; set; }
        public Nullable<int> MembershipID { get; set; }
    
        public virtual Membershipdata Membershipdata { get; set; }
        public virtual Membershipdata Membershipdata1 { get; set; }
    }
}
