//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInterstsData
    {
        public int ID { get; set; }
        public int PersonalID { get; set; }
        public int PInterestID { get; set; }
    
        public virtual PersonalInterest PersonalInterest { get; set; }
        public virtual Personaldata Personaldata { get; set; }
    }
}
