//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personaldata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personaldata()
        {
            this.CitizenAddresses = new HashSet<CitizenAddress>();
            this.CitizenIDs = new HashSet<CitizenID>();
            this.Educationsinfoes = new HashSet<Educationsinfo>();
            this.JobInfoes = new HashSet<JobInfo>();
            this.Membershipdatas = new HashSet<Membershipdata>();
            this.PersonalInterstsDatas = new HashSet<PersonalInterstsData>();
            this.Contactinfoes = new HashSet<Contactinfo>();
        }
    
        public int ID { get; set; }
        public string Firstname_EN { get; set; }
        public string MiddelName_EN { get; set; }
        public string Lastname_EN { get; set; }
        public string Firstname_Ar { get; set; }
        public string MiddelName_Ar { get; set; }
        public string Lastname_Ar { get; set; }
        public string Photopath { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitizenAddress> CitizenAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitizenID> CitizenIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Educationsinfo> Educationsinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobInfo> JobInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membershipdata> Membershipdatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInterstsData> PersonalInterstsDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactinfo> Contactinfoes { get; set; }
    }
}
