//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBTDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInterest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalInterest()
        {
            this.PersonalInterstsDatas = new HashSet<PersonalInterstsData>();
        }
    
        public int ID { get; set; }
        public string Interestdescription { get; set; }
        public Nullable<int> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInterstsData> PersonalInterstsDatas { get; set; }
    }
}
